dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
  - deploy
  - migrate
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      addons:
        mariadb: '10.2'
      install: skip
      before_script:
        - mysql -uroot < databases/create_databases.
        - ./gradlew wrapper
      script:
        - ./gradlew clean build
      before_deploy:
        - git config --local user.name "sjleea"
        - git config --local user.email "sjleea@lsis.com"
        - git tag -f $RELEASE_TAG
      deploy: &github
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "build/libs/lsis-service-server.jar"
        skip_cleanup: true

    - stage: deploy
      language: bash
      script:
        - echo "Downloading allocations server $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/sjleea_app/releases/download/$RELEASE_TAG/lsis-service-server.jar
      before_deploy:
        - echo "Deploying allocations server $RELEASE_TAG"
      deploy: &cloudfoundry
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE

    - stage: migrate
      language: java
      before_install:
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
      script:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
        - ./gradlew cfMigrate
